apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
   
spec:
  backend:
    serviceName: wordpress
    servicePort: 80

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    serviceName: nginx
    servicePort: 80
